/*
 * Sentinel LDK Runtime RESTful API  documentation
 *
 * This pages documents Sentinel LDK Runtime RESTful API Definition
 *
 * API version: 1.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ldklicensingretfulapi

type FeatureInfo struct {
	Concurrency *Concurrency `json:"concurrency,omitempty"`
	Detachable  bool         `json:"detachable,omitempty"`
	Disabled    bool         `json:"disabled,omitempty"`
	Expired     bool         `json:"expired,omitempty"`
	FeatureId   int32        `json:"featureId,omitempty"`
	ProductId   int32        `json:"productId,omitempty"`
	KeyId       int64        `json:"keyId,omitempty"`
	LicenseInfo *LicenseInfo `json:"licenseInfo,omitempty"`
	Locked      bool         `json:"locked,omitempty"`
	Name        string       `json:"name,omitempty"`
	Usable      bool         `json:"usable,omitempty"`
	Vmenabled   bool         `json:"vmenabled,omitempty"`
}

type FeaturesInfo struct {
	FeatureInfo []FeatureInfo `json:"feature,omitempty"`
	Count       int32         `json:"count,omitempty"`
}

type Features struct {
	FeatureInfo FeaturesInfo `json:"features,omitempty"`
}
